---
count: 8
default:
  restart: 1
  wait: 1
editor:
  files:
    base:
      - lib/Tail/Tool.pm
      - lib/Tail/Tool/File.pm
      - lib/Tail/Tool/Regex.pm
    more:
      - lib/Tail/Tool/RegexList.pm
      - lib/Tail/Tool/PostProcess.pm
      - lib/Tail/Tool/PreProcess.pm
    plugins:
      - lib/Tail/Tool/Plugin/GroupLines.pm
      - lib/Tail/Tool/Plugin/Spacing.pm
      - lib/Tail/Tool/Plugin/Replace.pm
    plugins2:
      - lib/Tail/Tool/Plugin/Highlight.pm
      - lib/Tail/Tool/Plugin/Ignore.pm
      - lib/Tail/Tool/Plugin/Match.pm
    other:
      - lib/Tail/Tool/Config.pm
      - bin/*
name: tailt
terminals:
  1a:
    command: ./Build && ./Build testcover
      - lib/Tail/Tool/Plugin/Replace.pm
    restart: 1
    wait: 0
    watch:
      - lib
      - bin
      - tests
  2:
    edit: base
  3:
    edit: more
  4:
    edit: plugins
  5:
    edit: plugins2
  6:
    edit: other
