=pod

=begin html

<a href="https://travis-ci.org/ivanwills/Tail-Tool"><img src="https://travis-ci.org/ivanwills/Tail-Tool.png" alt="Tail-Tool"></a>

=head1 Tail-Tool

Library for tailing files with plugins to enhance the output of the tail

=head1 INSTALLATION

To install this module, run the following commands:

    perl Build.PL
    ./Build
    ./Build test
    ./Build install

=head1 SUPPORT AND DOCUMENTATION

After installing, you can find documentation for this module with the
perldoc command.

    perldoc Tail::Tool

You can also look for information at:

    RT, CPAN's request tracker
        http://rt.cpan.org/NoAuth/Bugs.html?Dist=Tail-Tool

    AnnoCPAN, Annotated CPAN documentation
        http://annocpan.org/dist/Tail-Tool

    CPAN Ratings
        http://cpanratings.perl.org/d/Tail-Tool

    Search CPAN
        http://search.cpan.org/dist/Tail-Tool/

    Source Code
        git://github.com/ivanwills/Tail-Tool.git

=head1 COPYRIGHT AND LICENCE

Copyright (C) 2010-2014 Ivan Wills

This program is free software; you can redistribute it and/or modify it
under the terms of either: the GNU General Public License as published
by the Free Software Foundation; or the Artistic License.

See http://dev.perl.org/licenses/ for more information.

=cut
